name: Validate
on: workflow_call
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm --frozen-lockfile
      - run: pnpm tsc
      - uses: actions/cache@v3
        with:
          path: .eslintcache
          key: eslint-cache
      - run: pnpm lint:all
      - run: pnpm format:check
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.2
